### ISSUE TITLE
如何通过另外的方法（不通过自带的DOWNLOAD）  获取到编辑后的图像 

### ISSUE THREAD

**Issue by tonytu0510** [nhnent/toast-ui.vue-image-editor#9]
hello world~~~
我想保存编辑后的图片到数据库 请问有什么办法可以做到吗 谢谢

**Comment by tonytu0510** [comment]
`saveImg(){
        let lowerCas=this.$refs.tuiImageEditor.getRootElement().getElementsByClassName("lower-canvas")[0]
        let upperCas=this.$refs.tuiImageEditor.getRootElement().getElementsByClassName("upper-canvas ")[0]
        const canvasSize = this.$refs.tuiImageEditor.invoke('getCanvasSize')
        let width=canvasSize.width
        let height=canvasSize.height
        lowerCas.getContext("2d").drawImage(upperCas,0,0,width,height);
        // 把画布的内容转换为base64编码格式的图片
        let data = lowerCas.toDataURL( 'image/png', 1 );  //1表示质量(无损压缩)
        console.log(data)
      }`

**Comment by rodrigomata** [comment]
For further reference, I achieved it this way:

- Add a reference to your vue element:
`<tui-image-editor ref="tuiEditor" />`

- On your save method: 
```javascript
save() {
  const image = this.$refs.tuiEditor.editorInstance.toDataURL();
  console.log(image);
}
```

[Link](http://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#toDataURL) to the documentation

**Comment by tonytu0510** [comment]
en en thanks






在 2019-03-27 01:07:06，"Rodrigo Mata" <notifications@github.com> 写道：


For further reference, I achieved it this way:

Add a reference to your vue element:
<tui-image-editor ref="tuiEditor" />

On your save method:

save() {
  constimage=this.$refs.tuiEditor.editorInstance.toDataURL();
  console.log(image);
}

Link to the documentation
